config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chat_rooms, only: [:new, :create, :index]
  root 'chat_rooms#index'

  get 'chat_rooms/:random_hash', to: 'chat_rooms#show', as: :private_chat

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
# == Schema Information
#
# Table name: chat_rooms
#
#  id           :integer          not null, primary key
#  title        :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  random_hash  :string
#  recipient_id :integer
#

class ChatRoom < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: 'User', foreign_key: :recipient_id, optional: true

  has_many :messages, dependent: :destroy

  validates :title, presence: true
  validates :user_id, uniqueness: {scope: :recipient_id, message: 'only one valid pair'}

  scope :for_user, -> (id) {where('user_id = ? or recipient_id = ?', id, id).uniq}

  before_save do
    self.random_hash = SecureRandom.hex(4)
  end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  body         :text
#  user_id      :integer
#  chat_room_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.in_time_zone('EET').strftime('%H:%M on the %d %B %Y')
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  after_create_commit { PrivateChatCreatorJob.perform_later(self) }

  def name
    email.split('@')[0].try(:capitalize)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :load_chat_rooms

  private

  def load_chat_rooms
    @sidebar_chat_rooms = ChatRoom.for_user(current_user.id)#.where('user_id = ? or recipient_id = ?', current_user.id, current_user.id).uniq
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    if params[:q]
      @chat_rooms = ChatRoom.for_user(current_user).where('title like ?', "%#{params[:q]}%")
    else
      @chat_rooms = ChatRoom.for_user(current_user)
    end
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(random_hash: params[:random_hash])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  def apply_formatting(text)
    processed_text = text.split('').in_groups_of(100).map(&:join).join('<br>')
    processed_text =  processed_text.split(/\s+/).map {|t| t =~ /^https?:/ ? link_to(t, t) : t}.join(' ')
    urls = text.split(/\s+/).find_all { |u| u =~ /^https?:/ }
    if urls.any?
      begin
        object = LinkThumbnailer.generate(urls.first)
        [processed_text, image_tag(object.images[0].src.to_s, width: '200px', height: '100%')].join('<br>')
      rescue NoMethodError, URI::InvalidURIError
        processed_text
      end
    else
      processed_text
    end
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_chat_room.html.erb
<tr><td><%= link_to chat_room.title, private_chat_path(random_hash: chat_room.random_hash) %></tr></td>

app/views/chat_rooms/_form.html.erb
<%= form_for message, url: '#' do |f| %>
    <div class="form-group">
      <%= f.text_field :body, class: 'form-control', autocomplete: :off %>
      <small class="text-muted">From 2 to 1000 characters</small>
    </div>

    <%= f.submit "Post", class: 'hidden' %>
<% end %>

app/views/chat_rooms/index.html.erb
<h1><div style="text-align:center">Hello <%= current_user.name %> </div></h1>
<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>
<hr>
<%= form_tag chat_rooms_path, method: :get do %>
    <div class="form-group">
      <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Who are you searching for?', autocomplete: :off %>
    </div>
<% end %>

<table class="table table-striped">
  <thead>
    <th>Rooms</th>
  </thead>
  <tbody>
  <%= render @chat_rooms %>
  </tbody>
</table>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title.capitalize %></h1>
<hr>
<div id="messages" data-chat-room-id="<%= @chat_room.random_hash %>">
  <%= render @chat_room.messages %>
</div>

<%= render 'form', message: @message %>

app/views/layouts/_sidebar.html.erb
<%= cache @chat_rooms do %>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to 'RailsChat', root_path %>
    </li>
    <% @sidebar_chat_rooms.each do |chat_room| %>
        <li><%= link_to chat_room.title, private_chat_path(random_hash: chat_room.random_hash) %> </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liviucable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="wrapper">
    <%= render 'layouts/sidebar' %>
    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <%= link_to '<>', '#menu-toggle', id: 'menu-toggle', class: 'btn btn-active' %>
            <%= link_to("Hello #{current_user.name}", '#', class: 'btn btn-active') if user_signed_in? %>
            <%= link_to("Logout", destroy_user_session_path, method: :delete, class: 'btn btn-active pull-right') if user_signed_in? %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
  <!-- /#wrapper -->

  <!-- Menu Toggle Script -->
  <script>
      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
      });
  </script>
  </body>
</html>

app/views/messages/_message.html.erb
<%= cache message do %>
  <div class="card">
    <div class="card-block">
      <div class="row">
        <div class="col-md-1">
          <%= gravatar_for message.user %>
        </div>
        <div class="col-md-11">
          <p class="card-text">
            <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
            <%= content_tag(:span, raw(apply_formatting(message.body)), class: 'message-current') %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>